# Uncomment the next line to define a global platform for your project
# platform :ios, '10.0'

  use_frameworks!

target 'MoMagiciOSProject' do

  pod 'MomagiciOSSDK', :path=> "../MomagiciOSSDK/"

end
